import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import { SpotifyProvider } from "@/components/SpotifyContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-gray-50">
        <SpotifyProvider>
          <main>{children}</main>
          <footer className="mt-auto">
            <Footer />
          </footer>
        </SpotifyProvider>
      </body>
    </html>
  );
}
